events {
    worker_connections 1024;
}

http {
    upstream backend_servers {
        server server-a:8001;
        server server-b:8002;
    }

    server {
        listen 80;

        location = /favicon.ico {
            return 204;
            access_log off;
        }

        location / {
            proxy_pass http://backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header X-Served-By $upstream_addr always;
            
            
            add_header Cache-Control "no-store, no-cache, must-revalidate" always;
            proxy_hide_header Last-Modified;
            proxy_hide_header ETag;
        }
    }
}